
export enum AppScreen {
  SPLASH = 'SPLASH',
  ONBOARDING_1 = 'ONBOARDING_1',
  ONBOARDING_2 = 'ONBOARDING_2',
  ONBOARDING_3 = 'ONBOARDING_3',
  SIGNUP = 'SIGNUP',
  SIGNUP_UNDER_REVIEW = 'SIGNUP_UNDER_REVIEW',
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  OTP_VERIFICATION = 'OTP_VERIFICATION',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  WELCOME_BACK = 'WELCOME_BACK', // New PIN Screen
  
  // Main Tabs
  HOME = 'HOME',
  PAY_BILLS = 'PAY_BILLS',
  SCANNER = 'SCANNER',
  REWARDS = 'REWARDS',
  ME = 'ME',
  
  // Features
  TRANSACTION_HISTORY = 'TRANSACTION_HISTORY',
  TRANSACTION_DETAILS = 'TRANSACTION_DETAILS',
  RATES = 'RATES',
  NOTIFICATIONS = 'NOTIFICATIONS',
  AIRTIME = 'AIRTIME',
  BILL_PAYMENT_DETAILS = 'BILL_PAYMENT_DETAILS',
  BILL_PAYMENT_SUMMARY = 'BILL_PAYMENT_SUMMARY',
  SUGGESTION_BOX = 'SUGGESTION_BOX',
  ADD_MONEY = 'ADD_MONEY',
  VIRTUAL_ACCOUNT = 'VIRTUAL_ACCOUNT',
  USSD_DEPOSIT = 'USSD_DEPOSIT',
  CRYPTO_WALLET_SETUP = 'CRYPTO_WALLET_SETUP',
  BANK_ACCOUNT_SETUP = 'BANK_ACCOUNT_SETUP',
  CRYPTO_INVOICE = 'CRYPTO_INVOICE',
  CRYPTO_HUB = 'CRYPTO_HUB',
  
  // Receipt Flow (New)
  RECEIPT_OPTIONS = 'RECEIPT_OPTIONS',
  RECEIPT_IMAGE_PREVIEW = 'RECEIPT_IMAGE_PREVIEW',
  RECEIPT_PDF_PREVIEW = 'RECEIPT_PDF_PREVIEW',
  
  // Sell Flow
  COIN_SELECTION = 'COIN_SELECTION',
  NETWORK_SELECTION = 'NETWORK_SELECTION', // New
  COIN_RECEIVE = 'COIN_RECEIVE', // New (Address/QR)
  COIN_DETAIL = 'COIN_DETAIL', // Wallet Detail
  SELL_CRYPTO = 'SELL_CRYPTO', // Calculator
  SELL_SUMMARY = 'SELL_SUMMARY',
  SELL_SUCCESS = 'SELL_SUCCESS',
  SELL_PROCESSING = 'SELL_PROCESSING',
  SELL_FAILED = 'SELL_FAILED',
  SELL_REJECTED = 'SELL_REJECTED',
  
  // KYC Flow
  KYC_INTRO = 'KYC_INTRO',
  KYC_BVN = 'KYC_BVN',
  KYC_NIN = 'KYC_NIN',           
  KYC_ADVANCED_FORM = 'KYC_ADVANCED_FORM',
  KYC_PHONE_VERIFICATION = 'KYC_PHONE_VERIFICATION',
  KYC_UTILITY = 'KYC_UTILITY',   
  KYC_SELFIE = 'KYC_SELFIE',
  KYC_PIN_SETUP = 'KYC_PIN_SETUP',
  ONBOARDING_ADD_BANK = 'ONBOARDING_ADD_BANK',
  KYC_SUCCESS = 'KYC_SUCCESS',

  // New Screens
  BIOMETRIC_ENABLE = 'BIOMETRIC_ENABLE',
  NOTIFICATION_PERMISSION = 'NOTIFICATION_PERMISSION',
  ACCOUNT_OPENING_INFO = 'ACCOUNT_OPENING_INFO',
  WELCOME_TO_GOGREEN = 'WELCOME_TO_GOGREEN',
  WELCOME_TO_GOGREEN_ALT = 'WELCOME_TO_GOGREEN_ALT',
 
  // Me Section
  BANK_DETAILS = 'BANK_DETAILS',
  ADD_BANK = 'ADD_BANK',
  SECURITY = 'SECURITY',
  CHANGE_PIN = 'CHANGE_PIN',
  SUPPORT = 'SUPPORT',
  ACCOUNT_SETTINGS = 'ACCOUNT_SETTINGS',
  EDIT_PROFILE = 'EDIT_PROFILE',
  APP_UPDATE = 'APP_UPDATE',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  REFER_FRIEND = 'REFER_FRIEND',
  REFERRAL_WITHDRAW_CONFIRM = 'REFERRAL_WITHDRAW_CONFIRM',
  REPORT_BUG = 'REPORT_BUG',
  GUIDES_AND_TUTORIALS = 'GUIDES_AND_TUTORIALS',
  WITHDRAW_MONEY = 'WITHDRAW_MONEY',
  PAYMENT_SETTINGS = 'PAYMENT_SETTINGS',
  LOGGED_IN_DEVICES = 'LOGGED_IN_DEVICES',
  
  // Send Flow
  SEND_DESTINATION = 'SEND_DESTINATION',
  SEND_NEW_RECEIVER = 'SEND_NEW_RECEIVER',
  SEND_GOGREEN_SEARCH = 'SEND_GOGREEN_SEARCH',
  SEND_BANK_ACCOUNT = 'SEND_BANK_ACCOUNT',
  SEND_SELECT_ASSET = 'SEND_SELECT_ASSET',
  SEND_RECIPIENT = 'SEND_RECIPIENT',
  SEND_AMOUNT = 'SEND_AMOUNT',
  SEND_CONFIRM = 'SEND_CONFIRM',
  SEND_SUCCESS = 'SEND_SUCCESS',
  SEND_PROCESSING = 'SEND_PROCESSING',
  SEND_FAILED = 'SEND_FAILED',
  SEND_REJECTED = 'SEND_REJECTED',

  // Swap Flow
  SWAP_SELECT_ASSET_FROM = 'SWAP_SELECT_ASSET_FROM',
  SWAP_SELECT_ASSET_TO = 'SWAP_SELECT_ASSET_TO',
  SWAP_AMOUNT = 'SWAP_AMOUNT',
  SWAP_CONFIRM = 'SWAP_CONFIRM',
  SWAP_SUCCESS = 'SWAP_SUCCESS',
  BILL_PAYMENT_SUCCESS = 'BILL_PAYMENT_SUCCESS',
  WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS',
  WITHDRAW_PROCESSING = 'WITHDRAW_PROCESSING',
  WITHDRAW_FAILED = 'WITHDRAW_FAILED',
  WITHDRAW_REJECTED = 'WITHDRAW_REJECTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  KYC_UPLOADING = 'KYC_UPLOADING'
}

export interface SignupData {
  username: string;
  fullName: string;
  email: string;
  password: string;
  confirmPassword: string;
  referralCode?: string;
  referralSource?: string;
  country: string;
  profileImage?: string | null;
  phone?: string;
  autoWithdrawToBank: boolean;
  bvn?: string;
  nin?: string;
  selfie?: string;
}
