
export enum AppScreen {
  SPLASH = 'SPLASH',
  ONBOARDING_1 = 'ONBOARDING_1',
  ONBOARDING_2 = 'ONBOARDING_2',
  ONBOARDING_3 = 'ONBOARDING_3',
  SIGNUP = 'SIGNUP',
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  OTP_VERIFICATION = 'OTP_VERIFICATION',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  WELCOME_BACK = 'WELCOME_BACK', // New PIN Screen
  
  // Main Tabs
  HOME = 'HOME',
  PAY_BILLS = 'PAY_BILLS',
  SCANNER = 'SCANNER',
  REWARDS = 'REWARDS',
  ME = 'ME',
  
  // Features
  TRANSACTION_HISTORY = 'TRANSACTION_HISTORY',
  TRANSACTION_DETAILS = 'TRANSACTION_DETAILS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  AIRTIME = 'AIRTIME',
  BILL_PAYMENT_DETAILS = 'BILL_PAYMENT_DETAILS',
  BILL_PAYMENT_SUMMARY = 'BILL_PAYMENT_SUMMARY',
  SUGGESTION_BOX = 'SUGGESTION_BOX',
  ADD_MONEY = 'ADD_MONEY',
  CRYPTO_WALLET_SETUP = 'CRYPTO_WALLET_SETUP',
  BANK_ACCOUNT_SETUP = 'BANK_ACCOUNT_SETUP',
  
  // Receipt Flow (New)
  RECEIPT_OPTIONS = 'RECEIPT_OPTIONS',
  RECEIPT_IMAGE_PREVIEW = 'RECEIPT_IMAGE_PREVIEW',
  RECEIPT_PDF_PREVIEW = 'RECEIPT_PDF_PREVIEW',
  
  // Sell Flow
  COIN_SELECTION = 'COIN_SELECTION',
  NETWORK_SELECTION = 'NETWORK_SELECTION', // New
  COIN_RECEIVE = 'COIN_RECEIVE', // New (Address/QR)
  COIN_DETAIL = 'COIN_DETAIL', // Calculator
  SELL_SUMMARY = 'SELL_SUMMARY',
  SELL_SUCCESS = 'SELL_SUCCESS',
  
  // KYC Flow
  KYC_INTRO = 'KYC_INTRO',
  KYC_BVN = 'KYC_BVN',
  KYC_NIN = 'KYC_NIN',           
  KYC_UTILITY = 'KYC_UTILITY',   
  KYC_SELFIE = 'KYC_SELFIE',
  KYC_PIN_SETUP = 'KYC_PIN_SETUP',
  ONBOARDING_ADD_BANK = 'ONBOARDING_ADD_BANK',
  KYC_SUCCESS = 'KYC_SUCCESS',
 
  // Me Section
  BANK_DETAILS = 'BANK_DETAILS',
  ADD_BANK = 'ADD_BANK',
  SECURITY = 'SECURITY',
  CHANGE_PIN = 'CHANGE_PIN',
  SUPPORT = 'SUPPORT',
  ACCOUNT_SETTINGS = 'ACCOUNT_SETTINGS',
  EDIT_PROFILE = 'EDIT_PROFILE',
  APP_UPDATE = 'APP_UPDATE',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  REFER_FRIEND = 'REFER_FRIEND',
  REFERRAL_WITHDRAW_CONFIRM = 'REFERRAL_WITHDRAW_CONFIRM',
  REPORT_BUG = 'REPORT_BUG',
  WITHDRAW_MONEY = 'WITHDRAW_MONEY',
  PAYMENT_SETTINGS = 'PAYMENT_SETTINGS'
}

export interface SignupData {
  username: string;
  fullName: string;
  email: string;
  password: string;
  confirmPassword: string;
  referralCode?: string;
  country: string;
  profileImage?: string | null;
  phone?: string;
  autoWithdrawToBank: boolean;
}
