
export enum AppScreen {
  SPLASH = 'SPLASH',
  ONBOARDING_1 = 'ONBOARDING_1',
  ONBOARDING_2 = 'ONBOARDING_2',
  ONBOARDING_3 = 'ONBOARDING_3',
  SIGNUP = 'SIGNUP',
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  OTP_VERIFICATION = 'OTP_VERIFICATION',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  NOTIFICATION_PROMPT = 'NOTIFICATION_PROMPT',
  REFERRAL_POPUP = 'REFERRAL_POPUP',
  HOME = 'HOME',
  PAY_BILLS = 'PAY_BILLS',
  SCANNER = 'SCANNER',
  REWARDS = 'REWARDS',
  ME = 'ME',
  // KYC / Setup
  COMPLETE_SETUP = 'COMPLETE_SETUP',
  SET_PIN = 'SET_PIN',
  ADD_BANK = 'ADD_BANK',
  KYC_AUTH = 'KYC_AUTH',
  SELFIE_CAPTURE = 'SELFIE_CAPTURE',
  UTILITY_BILL = 'UTILITY_BILL',
  KYC_LOADING = 'KYC_LOADING',
  KYC_SUCCESS = 'KYC_SUCCESS',
  // Sell Crypto
  GENERATE_WALLETS = 'GENERATE_WALLETS',
  WALLET_GEN_LOADING = 'WALLET_GEN_LOADING',
  COIN_SELECTION = 'COIN_SELECTION',
  COIN_DETAIL = 'COIN_DETAIL',
  TX_PROCESSING = 'TX_PROCESSING',
  TX_SUCCESS = 'TX_SUCCESS',
  TRANSACTION_DETAILS = 'TRANSACTION_DETAILS',
  // Settings
  LINKED_BANKS = 'LINKED_BANKS',
  SECURITY_SETTINGS = 'SECURITY_SETTINGS',
  SUGGESTION_BOX = 'SUGGESTION_BOX',
  REPORT_BUG = 'REPORT_BUG'
}

export interface SignupData {
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  password: string;
  referralCode?: string;
}
